http_port 3128
visible_hostname aursmith-source-proxy
pid_filename /run/squid/squid.pid

cache deny all
access_log stdio:/dev/stdout
cache_log /dev/stderr

acl permitted_ports port 80 443
acl connect_method method CONNECT
acl tls_port port 443

acl forbidden_destination dst 0.0.0.0/8
acl forbidden_destination dst 10.0.0.0/8
acl forbidden_destination dst 100.64.0.0/10
acl forbidden_destination dst 127.0.0.0/8
acl forbidden_destination dst 169.254.0.0/16
acl forbidden_destination dst 172.16.0.0/12
acl forbidden_destination dst 192.0.0.0/24
acl forbidden_destination dst 192.0.2.0/24
acl forbidden_destination dst 192.168.0.0/16
acl forbidden_destination dst 198.18.0.0/15
acl forbidden_destination dst 198.51.100.0/24
acl forbidden_destination dst 203.0.113.0/24
acl forbidden_destination dst 224.0.0.0/4
acl forbidden_destination dst 240.0.0.0/4
acl forbidden_destination dst ::/128
acl forbidden_destination dst ::1/128
acl forbidden_destination dst fc00::/7
acl forbidden_destination dst fe80::/10
acl forbidden_destination dst ff00::/8

http_access deny !permitted_ports
http_access deny connect_method !tls_port
http_access deny forbidden_destination
http_access allow all

forwarded_for delete
request_header_access Via deny all
reply_header_access Via deny all
