services:
  controller:
    environment:
      AURSMITH_EXTERNAL_ARCHIVER_ENABLED: "false"
    networks:
      - control
      - agent
      - egress
      - edge
      - backbone

networks:
  backbone:
    external: true
    name: aursmith-backbone
